"""Initial migration

Revision ID: deb9b9aa4b49
Revises: 
Create Date: 2025-07-21 10:46:08.010967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deb9b9aa4b49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('image_link', sa.String(length=200), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('language')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('image_link')
        batch_op.drop_column('note')

    # ### end Alembic commands ###
